git-import-srpm: support non-conventional build directory through parsing %autosetup.
Signed-off-by: Quentin Casasnovas <quentin.casasnovas@vates.tech>

diff --git a/scripts/git-import-srpm b/scripts/git-import-srpm
--- a/scripts/git-import-srpm
+++ b/scripts/git-import-srpm
@@ -74,18 +74,27 @@ function get_build_dir() {
 
     check_spec_file "${worktree}" "${revision}"
 
-    local build_dirname=$(git -C "${worktree}" show "${revision}:${SPEC_FILE}" | \
-		   rpmspec --query --define "_topdir ${worktree}" --qf '%{name}-%{version}\n' /dev/stdin | \
-		   awk 'NR == 1'
-	    )
-    local build_dir="${worktree}/BUILD/${build_dirname}"
+    local build_dirname_query_filter
+    build_dirname_query_filter='%{name}-%{version}\n'
+    if [[ $(git -C "${worktree}" show "${revision}:${SPEC_FILE}" | grep '^%autosetup' ) =~ [[:space:]]-n[[:space:]]+([^[:space:]]+) ]]; then
+	build_dirname_query_filter="${BASH_REMATCH[1]}"
+    fi
+
+    local build_dirname
+    build_dirname=$(git -C "${worktree}" show "${revision}:${SPEC_FILE}" | \
+			rpmspec --query --define "_topdir ${worktree}" --qf "${build_dirname_query_filter}" /dev/stdin | \
+			awk 'NR == 1'
+		 )
+
+    local build_dir
+    build_dir="${worktree}/BUILD/${build_dirname}"
     if [[ ! -d "${build_dir}" ]] ; then
 	# rpmbuild version 6.x are building in a sub-directory
         build_dir="${worktree}/BUILD/${build_dirname}-build/${build_dirname}"
     fi
 
     if [[ ! -d "${build_dir}" ]]; then
-	echo "Could not infer an existing build directory"
+	echo "Could not infer an existing build directory from ${build_dirname}" 1>&2
 	exit 1
     fi
     echo "${build_dir}"
